readme: ../README.md

custom_categories:
  - name: Configuration and Feedback
    children:
    - OTOnexus
    - OTONotification
    - OTOnexusLocationDelegate

  - name: Capture
    children:
    - OTOCaptureViewController
    - OTOCaptureViewDelegate

  - name: Models
    children:
    - OTOSession
    - OTOSessionDelegate
    - OTOExperience
    - OTOProduct
    - OTOBarcode
    - OTOBarcodeType

  - name: Platform Modules
    children:
    - OTOModule
    - OTOImageUploadModule
    - OTOGudidModule
    - OTOVideoModule
    - OTOGs1ValidationModule
    - OTOTextModule
    - OTOSurveyModule
    - OTOCustomValidationModule
  
  - name: GUDID Responses
    children:
    - OTOLookupSuccessResponse
    - OTOLookupFailureResponse

  - name: GS1 Validation Response
    children:
    - OTOValidateBarcodeResponse

  - name: Custom Validation Response
    children:
    - OTOCustomValidateBarcodeResponse

  - name: Survey Question Type
    children:
    - OTOSurveyQuestion
    - OTOSurveyDateQuestion
    - OTOSurveySelectQuestion
    - OTOSurveyTextQuestion

  - name: Error 
    children:
    - OTOError

exclude:
  - Classes/Models/Modules/OTOReorderModule.swift
  - Classes/Models/Modules/OTOSafetyCheckModule.swift
  - Classes/Models/ActionResponses/OTOReorderResponse.swift
  - Classes/Models/ActionResponses/OTOSafetyCheckResponse.swift
  - Classes/Models/ActionResponses/OTOLookupActionResponse.swift
  - Classes/Models/ActionResponses/OTOActionResponse.swift

